import type { FloatingIconConfig } from "~/components/floating-tech-icon";

export const floatingIconsConfig: FloatingIconConfig[] = [
  {
    component: "Firebase",
    label: "Firebase",
    x: 10,
    y: 20,
    delay: 0,
    speed: 20,
    animationType: "float",
  },
  {
    component: "GoogleCloud",
    label: "Google Cloud",
    x: 85,
    y: 15,
    delay: 1,
    speed: 22,
    animationType: "float-alt",
  },
  {
    component: "GoogleDevelopers",
    label: "GDG",
    x: 15,
    y: 70,
    delay: 2,
    speed: 18,
    animationType: "float-bounce",
  },
  {
    component: "TensorFlow",
    label: "TensorFlow",
    x: 80,
    y: 75,
    delay: 3,
    speed: 19,
    animationType: "float",
  },
  {
    component: "Flutter",
    label: "Flutter",
    x: 20,
    y: 45,
    delay: 4,
    speed: 23,
    animationType: "float-alt",
  },
  {
    component: "Angular",
    label: "Angular",
    x: 75,
    y: 40,
    delay: 5,
    speed: 21,
    animationType: "float-bounce",
  },
  {
    component: "Android",
    label: "Android",
    x: 12,
    y: 85,
    delay: 1.5,
    speed: 20,
    animationType: "float",
  },
  {
    component: "Gemini",
    label: "Gemini AI",
    x: 88,
    y: 60,
    delay: 2.5,
    speed: 22,
    animationType: "float-alt",
  },
  {
    component: "Gemma",
    label: "Gemma",
    x: 25,
    y: 30,
    delay: 3.5,
    speed: 19,
    animationType: "float-bounce",
  },
  {
    component: "Chrome",
    label: "Chrome",
    x: 70,
    y: 85,
    delay: 4.5,
    speed: 21,
    animationType: "float",
  },
  {
    component: "DevFest",
    label: "DevFest",
    x: 30,
    y: 60,
    delay: 0.5,
    speed: 20,
    animationType: "float-alt",
  },
  {
    component: "Google",
    label: "Google",
    x: 65,
    y: 25,
    delay: 1.8,
    speed: 18,
    animationType: "float-bounce",
  },
  {
    component: "Gemini",
    label: "Gemini AI",
    x: 50,
    y: 10,
    delay: 5.5,
    speed: 23,
    animationType: "float",
  },
  {
    component: "GoogleCloud",
    label: "Google Cloud",
    x: 92,
    y: 35,
    delay: 6,
    speed: 19,
    animationType: "float-alt",
  },
  {
    component: "Chrome",
    label: "Chrome",
    x: 5,
    y: 50,
    delay: 2.8,
    speed: 22,
    animationType: "float-bounce",
  },
  {
    component: "Gemma",
    label: "Gemma",
    x: 95,
    y: 80,
    delay: 4.2,
    speed: 20,
    animationType: "float",
  },
];
